[package]
name = "hero_forester"
version = "0.1.0"
authors = ["vitautart <vitartach@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
raylib = "3.0.0"
