#ifndef GLOBALS_H
#define GLOBALS_H

#define TSIZE 32

typedef enum
{
    TEXTURE_ID_PLAYER_1,
    TEXTURE_ID_PLAYER_2,
    TEXTURE_ID_PLAYER_3,
    TEXTURE_ID_PLAYER_4,
    TEXTURE_ID_PLAYER_5,
    TEXTURE_ID_PLAYER_6,
    TEXTURE_ID_PLAYER_7,
    TEXTURE_ID_PLAYER_8,
    TEXTURE_ID_TREE_1,
    TEXTURE_ID_TREE_2,
    TEXTURE_ID_TREE_3,
    TEXTURE_ID_TREE_4,
    TEXTURE_ID_TREE_5,
    TEXTURE_ID_TREE_6,
    TEXTURE_ID_TREE_7,
    TEXTURE_ID_TREE_8,
    TEXTURE_ID_ENEMY_1,
    TEXTURE_ID_ENEMY_2,
    TEXTURE_ID_ENEMY_3,
    TEXTURE_ID_ENEMY_4,
    TEXTURE_ID_ENEMY_5,
    TEXTURE_ID_ENEMY_6,
    TEXTURE_ID_ENEMY_7,
    TEXTURE_ID_ENEMY_8,
    TEXTURE_ID_GRASS_1,
    TEXTURE_ID_GRASS_2,
    TEXTURE_ID_GRASS_3,
    TEXTURE_ID_GRASS_4,
    TEXTURE_ID_GRASS_5,
    TEXTURE_ID_GRASS_6,
    TEXTURE_ID_GRASS_7,
    TEXTURE_ID_GRASS_8,
    TEXTURE_ID_MAX_VALUE
} texture_id_t;

#endif // GLOBALS_H
